language: php

services:
    - mysql
    - postgresql

sudo: false

cache:
    directories:
        - vendor
        - $HOME/.composer/cache

php:
    - 7.0
    - 7.1

install:
    - composer install --no-interaction --prefer-source

before_script:
    # Init Postgre database
    - psql -c 'CREATE DATABASE inline;' -U postgres
    - psql inline < tests/sql/postgres.sql

    # Init Mysql database
    - mysql -e 'CREATE DATABASE IF NOT EXISTS inline;' -u root
    - mysql -u root inline < tests/sql/mysql.sql

script:
    - phpunit --coverage-clover coverage.xml

after_script:
    # Report Code Coverage
    - >
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      && php coveralls.phar --verbose --config .coveralls.yml
